### ISSUE TITLE
Tag #swagger.paths change to #swagger.path

### ISSUE THREAD

**Issue by LuisLenta** [davibaltar/swagger-autogen#139]
Hello there.

I'm using swagger-autogen for my projects. After updating to version 2.20.8 with npm, I found a problem. 

All my endpoints include the tag #swagger.**paths** = [/route/endpoint] but in the new version the tag should be #swagger.**path** =  [/route/endpoint]. 

* Notice the tag conversion from plural to singural. 

After changing all tags the problem gets fixed. 

I did not know where to upload this bug, if this is not the right place I apologize

@davibaltar thanks for all support.

**Comment by davibaltar** [comment]
Hi @LuisLenta! Thank you for opening the issue. 

I didn't know that the `#swagger.paths` tag was recognized. Officially the lib recognizes the  `#swagger.path` tag. Because of some bugs, I had to restrict some tags, I think because of this the `#swagger.paths` is no long recognized. But was good you bring this, because some people may have the same problem. For this case, the correct is update to `#swagger.path` as you did.

Thank you!
