### ISSUE TITLE
Swagger Dark Mode

### ISSUE THREAD

**Issue by PauloFavero** [davibaltar/swagger-autogen#142]
HI Davi, 

Is it possible to add a dark theme feature in swagger-autopen?
Here is an [example](https://dev.to/amoenus/turn-swagger-theme-to-the-dark-mode-4l5f) to inspire.

Best,
Paulo

**Comment by davibaltar** [comment]
Hi @PauloFavero! Thank you for opening the issue. 

swagger-autogen just generates the .json file with the Swagger specification. Styles you'll have to change in the lib that interprets the .json file and displays the Swagger-UI, such as `swagger-ui-express`, for example. 

Because it's not in the scope of the swagger-autogen, I'll be closing the issue.
