### ISSUE TITLE
Is it possible to auto detecting type?

### ISSUE THREAD

**Issue by handikacatur** [davibaltar/swagger-autogen#166]
Is it possible to auto detecting field type inside the body?

**Comment by davibaltar** [comment]
Hi @handikacatur ! Thank you for opening the issue. 

For JS, unfortunately it is not possible because JS it is weakly typed. For TS there are some possibilities and there is an issue about this here #162. Any progress about TS, I'll post in the #162. Because of this, I'm closing this issue. 

Thnks
