### ISSUE TITLE
swagger-output.json file isn't generated and no errors are thrown.

### ISSUE THREAD

**Issue by Apurva-Nagar** [davibaltar/swagger-autogen#170]
Hi, I was trying to add swagger-autogen to a newly started project, but the `swagger-out.json` file isn't generated and no errors are shown either. Is there any compatibility issue that I'm unaware of or am I just doing something wrong? 

Node version: 16.17.0
Express: 4.18.1
Import Type: ES5 Module imports

Repo Link - https://github.com/NovelThoughts/iClass-BE

Thanks.

**Comment by davibaltar** [comment]
Hi @Apurva-Nagar! Thank you for opening the issue and for the sample project.

For now, the swagger-autogen doesn't recognise relative paths, so for now, you'll need to change your relative path `../index.js` to `./index.js`. But there is an opened issue about this #159 and I hope fix it as soon as possible.

Another thing it's the `()` missing on the function `swaggerAutogen`:

Instead of: 
`swaggerAutogen(outputFile, endpointsFiles, doc);`

Change to:
`swaggerAutogen()(outputFile, endpointsFiles, doc);`

How it's a known issue, I'm going to close it, but if this changes doesn't work there, let me know.

**Comment by Apurva-Nagar** [comment]
Thanks, that worked 😃
