### ISSUE TITLE
Express Request/Response bodies

### ISSUE THREAD

**Issue by Arjan-Zuidema** [davibaltar/swagger-autogen#215]
Hi!

I want to generate an openapi spec file from my code and this package looks like what I need. But it does not seem to work (yet). It does not detect the request and response bodies properly.

```js
import { NextFunction, Request, Response, Router } from "express";
import { CreateRequestBody } from "../../../types/request";
import { CreateResponseBody } from "../../../types/response";

const router = Router();

router.post(
  "/create",
  async (req: Request<{}, {}, CreateRequestBody>, res: Response<CreateResponseBody>, next: NextFunction) => {
    // Create code
  }
);
```

I am using the config as described in [Usage basic](https://github.com/davibaltar/swagger-autogen#usage-basic)

I am doing something wrong or need more configuration? Or is this not (yet) supported? (I tried the search, but don't really know what to search for)

**Comment by davibaltar** [comment]
Hi @Arjan-Zuidema. Thank you for opening the issue. 

Unfortunately the lib doesn't support this kind of code yet, but it's in my TODO list to handle it. There is an issue opened about this (#175), so any news about it I'll post there. Because of this I'll close this issue. But thank you for the code, I'll use it to help me when I'm handling the problem.
