### ISSUE TITLE
Can't edit data

### ISSUE THREAD

**Issue by hsiangfeng** [davibaltar/swagger-autogen#31]
I data default is down below

```
{
  "data": {
    "Id": "ID (String)",
    "num": "5(Number)"
  }
}
```

![圖片](https://user-images.githubusercontent.com/19990752/110922390-98df5300-835a-11eb-82e9-db16377a0285.png)

default can execute.

but now I edit to...

```
{
  "data": {
    "Id": "1",
    "num": 10
  }
}
```

now can't execute, but in the case of

```
{
  "data": {
    "Id": "1",
    "num": "10"
  }
}
```

is working.

**Comment by davibaltar** [comment]
Hi @hsiangfeng. Swagger-autogen recognizes the type automatically based on the value and builds the model. In your case, if you want the "num" field to be of the number type, just enter any number in the value. For example:

Instead of:
```
{
  "data": {
    "Id": "ID (String)",
    "num": "5(Number)"
  }
}
```

See the model in this case:

![1](https://user-images.githubusercontent.com/9805564/111015151-2d12df80-8386-11eb-89f4-b1d5c1d110c8.png)

Switching to a number:

```
{
  "data": {
    "Id": "ID (String)",
    "num": 5
  }
}
```
See the model:

![2](https://user-images.githubusercontent.com/9805564/111015185-5895ca00-8386-11eb-8271-66f0676929e1.png)

In this case, the "num" field will allow a number type.

**NOTE:** The swagger-ui-express (responsible for building the UI) allows the string type to be passed in the numeric fields, but, otherwise, this is not allowed, I don't know why.

Try it and tell me if it doesn't work.

**Comment by hsiangfeng** [comment]
Hi, @davibaltar  is working . 

thx : )
