### ISSUE TITLE
Cannot be generated automatically

### ISSUE THREAD

**Issue by hsiangfeng** [davibaltar/swagger-autogen#6]
I use Express.

My router is written down

```
router
  .put('/xxx', () => {})
  .post('/xxx', () => {})
  .post('/xxx/:id', () => {})
```

I found that writing like this is invalid.

If you change it like this, it will work

```
router.put('/xxx', () => {})
router.post('/xxx', () => {})
router.post('/xxx/:id', () => {})
```

so...
Can't use the first way of writing?

**Comment by pratikIT95** [comment]
Hi, I'm not a maintainer for this code base, but I faced a similar issue before. 

There is a closed issue for this one and the latest version should resolve it. I suggest you to install the latest version.

**Comment by davibaltar** [comment]
Hi hsiangfeng!

As pratikIT95 said, this has been fixed in the latest version. Update with:

`npm install --save swagger-autogen@2.1.0`

**Comment by hsiangfeng** [comment]
@pratikIT95 & @davibaltar 

Thanks for answering. : )

But.
I am using the latest version as invalid > `swagger-autogen": "^2.1.0",`

Here is my example

[example](https://github.com/hsiangfeng/expressSwagger)

can be seen

[router/index.js](https://github.com/hsiangfeng/expressSwagger/blob/main/routes/index.js)

and 

[router/user.js](https://github.com/hsiangfeng/expressSwagger/blob/main/routes/users.js)

is different writing methods.

But it can only output [router/user.js](https://github.com/hsiangfeng/expressSwagger/blob/main/routes/users.js)

Is my setting incorrect?

**Comment by davibaltar** [comment]
Hi hsiangfeng. I identified the problem. It occurs for two factors.

1. As you are working with routes, you need to pass the 'root' of your route as your endpoint file, which in your case is the app.js file. Then your swagger.js will look like this:


`const swaggerAutogen = require('swagger-autogen')();`

`const outputFile = './swagger_output.json';`
`const endpointsFiles = ['./app.js'];`

`swaggerAutogen(outputFile, endpointsFiles)`


2. Through your example it was possible to identify a bug in lib .. :( to work around the problem for now, in your routes/index.js file, do not break the line of the first method after the "router", that is, instead of doing:

router
     .get (...
     .post (...
     .put (...


do it:

  router.get (...
     .post (...
     .put (...

Here it worked! This "breaking the line" bug after the "route" I will resolve here as soon as possible. Try it there and see if it works.

Thank you for reporting this issue!

**Comment by hsiangfeng** [comment]
@davibaltar oh! is working!

Thanks a lot too you library, I really like it. : )

I look forward to its correction.

**Comment by davibaltar** [comment]
Thanks hsiangfeng! If you have more problems, report it to us.

I published now the version 2.1.1 to fix this bug.
I will keep this issue open for a while if someone has the same problem and has an old version.

**Comment by hsiangfeng** [comment]
Thanks @davibaltar! new version is working!

If it is changed to this, it will be invalid

```
router
  .use(middleware)
  .put('/xxx', () => {})
  .post('/xxx', () => {})
  .post('/xxx/:id', () => {})
```

But it works if it is like this

```
router.use(middleware)
  .put('/xxx', () => {})
  .post('/xxx', () => {})
  .post('/xxx/:id', () => {})
```

**Comment by davibaltar** [comment]
Hi @hsiangfeng. Thanks for letting me know. Really I forgot to verify the "use" case. In the next version I will publish with this correction. Any other problem, let us know. Thanks!

**Comment by davibaltar** [comment]
Hi @hsiangfeng. The version 2.2.1 fixed this. If the problem persists in your project, please open a new issue with more details, please.
