### ISSUE TITLE
Set definitions for common status codes in swagger.js through options object

### ISSUE THREAD

**Issue by vignesh87ad** [davibaltar/swagger-autogen#75]
Hello,

I was wondering if we could automatically set the definitions for common status codes like 500, 404 etc.. in the swagger.js file using the options object. Here is my idea for the same.

/* swagger.json */

```
const options = {
    openapi: null,  
    language: 'en-US',    
    disableLogs: false, 
    disableWarnings: false,
    statusDefinitions: {
        401: {'$ref': '#/definitions/ErrorResponse'},
        404: {'$ref': '#/definitions/ErrorResponse'},
        500: {'$ref': '#/definitions/ErrorResponse'}
    }
}

const swaggerAutogen = require('swagger-autogen')(options);

```

/* swagger-autogen.js */

```
const tables = require('./src/tables');

...

module.exports = function(args) {
    ...
    tables.setHttpStatusDefinitions(options.statusDefinitions);
}

```

/* src/tables.js */

```
var tableStatusDefinitions = {};

...

function setHttpStatusDefinitions(statusDefinitions) {
    tableStatusDefinitions = statusDefinitions;
}

function getHttpStatusDefinitions(statusCode, lang) {
    return tableStatusDefinitions[statusCode];
}

module.exports = {
    ...
    setHttpStatusDefinitions,
    getHttpStatusDefinitions
}

```

/*  src/handle-data.js (not sure which lines exactly) */

```

objResponses[status] = {
    description: tables.getHttpStatusDescription(status, swaggerTags.getLanguage()),
    schema: tables.getHttpStatusDefinitions(status, swaggerTags.getLanguage())
};

```

**Comment by davibaltar** [comment]
Hi @vignesh87ad! Thanks for the suggestion! 

I'll evaluate this case and if it's compatible with the idea of the module, we'll implement it.

**Comment by davibaltar** [comment]
The version 2.18.0 has implemented a solution to this.

Thinking about flexibility, now is possible to declare the swagger properties in the route root middleware. In your case, you can do for example:

```js
...
app.use('/v1', routesV1
    /* #swagger.responses[500] = {
            ifStatusPresent: true,
            schema: { $ref: '#/definitions/someSchemaTo500' }
    } */
...
```

NOTE: By default, the `ifStatusPresent` parameter is false. If true, only endpoints that contain the 500 status code will receive the schema declared in `#swagger.responses[500] = ...` Otherwise, 500 status code will not be shown. If the `ifStatusPresent` is false or missing, all endpoints belongs to '/v1' will receive the 500 status code with the schema declared in `#swagger.responses[500] = ...`.

See more about it here: [Properties Inheritance](https://github.com/davibaltar/swagger-autogen#properties-inheritance)

If it doesn't work, let me know, please.
