### ISSUE TITLE
Global error handling middleware is not recognized

### ISSUE THREAD

**Issue by kamurashev** [davibaltar/swagger-autogen#77]
I have next block of code at the end of my server.js file:
```
app.use((err, req, res, next) => {
  /*#swagger.responses[500] = {
      description: 'Server error. Object with msg field representing detailed reason',
      schema: { $ref: '#/definitions/ErrorMessage' }
  }*/
  const errResp = { msg: err.message };
  console.error('500 - Internal server error has occured', errResp);
  res.status(500).json(errResp);
});
```
By design it handles any uncaught errors and return them as status 500 + description, unfortunately I do not see 500 response code being added to all the API endpoints into swagger.json as I expect it to. 

...as a separate idea it would probably be handy to have an ability to specify global (being applied to all the endpoints) responses into the doc obj.

With my code implementation and current lib state the only workaround I have is  to either specify 500 response for each and every endpoint separately which kind of jeopardizes the whole idea or not document 500 at all.

**Comment by davibaltar** [comment]
Hi @kamurashev! Thank you for the suggestion! I'll evaluate this case.

#75

**Comment by davibaltar** [comment]
The version 2.18.0 has implemented a solution to this.

Thinking about flexibility, now is possible to declare the swagger properties in the route root middleware. In your case, you can do for example:

```js
...
app.use('/v1', routesV1
    /* #swagger.responses[500] = {
            ifStatusPresent: true,
            schema: { $ref: '#/definitions/someSchemaTo500' }
    } */
...
```

NOTE: By default, the `ifStatusPresent` parameter is false. If true, only endpoints that contain the 500 status code will receive the schema declared in `#swagger.responses[500] = ...` Otherwise, 500 status code will not be shown. If the `ifStatusPresent` is false or missing, all endpoints belongs to '/v1' will receive the 500 status code with the schema declared in `#swagger.responses[500] = ...`.

See more about it here: [Properties Inheritance](https://github.com/davibaltar/swagger-autogen#properties-inheritance)

If it doesn't work, let me know, please.
