### ISSUE TITLE
Not able to genrate array type response

### ISSUE THREAD

**Issue by lahoti-piyush** [davibaltar/swagger-autogen#8]
in request and response not able to generate documentation for array request and response
I have defined like
```
/* #swagger.responses[200] = { "description": "successful operation",
    "schema": {
      "type": "array",
      "items": {
        $ref: "#/definitions/NotificaitonPrefernece"
      }
    }
} */
```
Generate output:

```
"responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "array"
                },
                "items": {
                  "xml": {
                    "name": "notificaitonprefernece"
                  },
                  "$ref": "#/definitions/NotificaitonPrefernece"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          }
}
```

expected:
```
"responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/NotificaitonPrefernece"
              }
            }
          },
          }
```

**Comment by davibaltar** [comment]
Hi @lahoti-piyush!

Thanks for opening the issue. If you correct { ... "type": "object" ... } to { ... "type": "array" ... }, manually, will your "NotificaitonPrefernece" return as expected?

I want to understand if the problem is just the { ... "type": "object" ... } that is not becoming { ... "type": "array" ... } or if there are more things beyond that.

**Comment by fersampieri** [comment]
Hi,

I am facing a similar issue trying to use arrays

If i want to define a response as an array of strings, I am trying this code:

```
/*
  #swagger.tags = ['Something']
  #swagger.responses[200] = {
    description: 'Array of strings',
    schema: {
      type: "array",
      items: {
          type: "string"
      }
    }
  }
*/
```

which is generating the following section in swagger.json:
```
"responses": {
  "200": {
    "description": "Array of strings",
    "schema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "example": "array"
        },
        "items": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "example": "string"
            }
          }
        }
      },
      "xml": {
        "name": "main"
      }
    }
  }
}
```

it represents an object with attributes "type" and "items" instead of the expected array of strings

![image](https://user-images.githubusercontent.com/59127168/105384875-7ef28100-5bf1-11eb-9160-0e9f07d6097b.png)

The expected results can be achieved modifying manually the swagger.json

```
"responses": {
  "200": {
    "description": "Array of Assignments returned",
    "schema": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "xml": {
        "name": "main"
      }
    }
  }
}
```

with the following (and expected) result:

![image](https://user-images.githubusercontent.com/59127168/105385487-2c659480-5bf2-11eb-98c5-f7f29c7fba0b.png)

This example is just an array of strings, but it is also failing if I use a $ref as an item's type (it should return an array of $ref)

Thanks!

**Comment by davibaltar** [comment]
Hi @fersampieri. 

Only the schema of the module's responses works differently from the official Swagger specifications. You don't need to pass the "item" and "type" in the schema. Just declare directly in the schema how you want to see the answer. In your case, try this:

```
/*
  #swagger.tags = ['Something']
  #swagger.responses[200] = {
    description: 'Array of strings',
    schema: [
        "string"
    ]
  }
*/
```

Tell me if it worked on your case, please.

**Comment by fersampieri** [comment]
Hi,

Thanks for the quick response, and yes, your suggestion worked fine. However, It forces me to declare another definition of the same object.

Please consider the following example:

```
definitions: {
  myObject: {
    field: 'fieldText'
    ... more fields ...
  }
}
```

If I have endpoint (A) returning a single myObject and another endpoint (B) returning an array of them, in order to follow your suggestion I would need to create another definition for my array of myObjects:

```
definitions: {
  myObject: {
    field: 'fieldText'
    ... more fields ...
  },
  arrayOfMyObject: [
    {
        field: 'fieldText'
        ... more fields ...
     }
  ]
}
```

Am I right? Is that behavior intentional? I read all the docs again in case I am missing something but I couldn't find the sintaxis I should use to set up an array of a single object reference. 

According to the swagger specifications it is posible to configure an array of an existing object without having to declare it again inside an array. i.e.:

```
"responses": {
          "200": {
            "description": "Something",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/myObject"
              }
            }
          },
 }
```


Is there any way to do that with this library?

Thanks again!

**Comment by davibaltar** [comment]
Yes @fersampieri, there is a way to do this. But I really hadn't thought of this case (array of objects) when I created the documentation. But the answer to that is:

Definitions:  
```
definitions: {
        myObject: {
            field: "fieldText"
        },
        myArray: [
            { $ref: "#/definitions/myObject" }
        ],
        ...
```

In the endpoint:  
```
/*
  #swagger.tags = ['Something']
  #swagger.responses[200] = {
    description: 'object',
    schema: { "$ref": "#/definitions/myObject" }
  }
*/
```
or
```
/*
  #swagger.tags = ['Something']
  #swagger.responses[200] = {
    description: 'Array of objects',
    schema: { "$ref": "#/definitions/myArray" }
  }
*/
```
Thanks for bringing this up! The documentation doesn't really contain these examples .. :( 
I will review all of these cases, like object array, string array, etc. to see if they are OK and I will add these examples in the documentation. If you have any other problems, tell us.

E tell me if it worked on your case, please.

**Comment by fersampieri** [comment]
Sorry, but it is not working. 

`Swagger-autogen:  Failed × `

This is my definitions section:

```
"definitions": {
	"myObject": {
		"field": "value"
	},
	"myObjectArray": [
		{ "$ref": "#definitions/myObject" }
	]
}
```

It doesn't matter if I use any of these schemas in any endpoint, in fact, in this test I am not even using them. It just fails when I add "myObjectArray" definition ("myObject" definition works fine).

```
TypeError: Cannot read property 'replaceAll' of undefined
    at formatDefinitions (******\node_modules\swagger-autogen\src\swagger-tags.js:34:56)
    at ******\node_modules\swagger-autogen\src\swagger-tags.js:56:39
    at Array.forEach (<anonymous>)
    at Object.formatDefinitions (******\node_modules\swagger-autogen\src\swagger-tags.js:53:29)
    at ******\node_modules\swagger-autogen\swagger-autogen.js:64:71
    at Array.forEach (<anonymous>)
    at ******\node_modules\swagger-autogen\swagger-autogen.js:63:49 {stack: 'TypeError: Cannot read property 'replaceAll' …ules\swagger-autogen\swagger-autogen.js:63:49', message: 'Cannot read property 'replaceAll' of undefined'}
```

I am using: `"swagger-autogen": "^2.4.1"`

And, actually, this is the same error (and stack trace) obtained if I add this config in my endpoint:

```
/*
  #swagger.tags = ['Something']
  #swagger.responses[200] = {
    description: 'Array of myObject',
    schema: {
      type: "array",
      items: {
          type: {
            $ref: "#definitions/myObject"
          }
      }
    }
  }
*/```

So, probably, fixing this, I would be able to use the code I tried in my first comment :)

**Comment by davibaltar** [comment]
I believe this may be happening because of the "/" symbol that is missing after the "#" in your: `{ $ref: "#definitions/myObject" }` in the definition. Switch to:

```
{ $ref: "#/definitions/myObject" }
```

and check if it will work.

**Comment by lahoti-piyush** [comment]
> Hi @lahoti-piyush!
> 
> Thanks for opening the issue. If you correct { ... "type": "object" ... } to { ... "type": "array" ... }, manually in the .json file, will your "NotificaitonPrefernece" return as expected?
> 
> Another thing, you don't need to put the "type" and "items" inside the "schema", this is made automatically. Try the following code instead:
> 
> ```
> /* #swagger.responses[200] = { 
>         description: "successful operation",
>         schema: { $ref: "#/definitions/NotificaitonPrefernece" }
> } */
> ```
> 
> If the above code is unsuccessful, post your "NotificaitonPrefernece".

@davibaltar 
changing  { ... "type": "object" ... } to { ... "type": "array" ... },  wont make a difference.
NotificaitonPrefernece 
if change to schema: { $ref: "#/definitions/NotificaitonPrefernece" } then how automatically it take as array??

**Comment by lahoti-piyush** [comment]
Thanks @davibaltar ,
I have tried

**Comment by fersampieri** [comment]
Hi @davibaltar,

sorry, It was my mistake. Now it is working.

Thanks for your time.
