### ISSUE TITLE
Does Not Recognise Array Parameters in Body

### ISSUE THREAD

**Issue by irzakamran99** [davibaltar/swagger-autogen#99]
Hello @davibaltar!

When I run swagger auto-gen to generate the JSON file, it does not correctly recognise arrays of json objects as parameters for POST and PUT body objects.

For example, in this POST API body, stops is an array of json objects but it appears as a variable of type any in on the swagger-UI.
<img width="1247" alt="Screen Shot 2021-11-18 at 6 48 58 PM" src="https://user-images.githubusercontent.com/86774070/142427943-7a80c4c6-2c61-45e5-8685-707410b0f459.png">

This is what an array of stop objects looks like:
`{"stops":[{
        "user_id":1,
        "priority":1,
        "items":[
            {"user_id":4444,"order_id":1}
        ]
    },
    {
        "user_id":2,
        "priority":1,
        "items":[
            {"user_id":5555,"order_id":1}
        ]
    }]
}`

I want the swagger-UI to display it as an array of objects with all object properties clearly defined for the user. 

Please let me know if I can clarify the problem. I hope you can help me solve this issue. Thanks in advance!

**Comment by davibaltar** [comment]
Hi @irzakamran99. Thank you for opening the issue.

About that, arrays are so hard to recognise, because there are many ambiguous situations, for example:

```js
router.post('/path', (req, res) => {
    let { property1, property2 } = req.body;

    var test = req.body.property3;
})
```

There is no a simple way to identify if the property1, property2 and property3 are of type String, Object or Array. Remember that the swagger-autogen just do a parse from a static file. 

Maybe in the future versions, be possible identify some things from some 'clues' in the code, such as:

```js
router.post('/path', (req, res) => {
    let { property1, property2 } = req.body;
 
    var someVar1 = property1[0];   // property1 is an Array. But what is the Array type?

    var someVar2 = property2.subItem;   // property2 is an Object. But what is the 'subItem' type?

})
```

In the future will be possible to improve the auto-recognition using this clues that I said like `property1[0]` or `property2.subItem`, but this is still very limited.
